### PR TITLE
Fixes #392, detach for statically provisioned volumes. 

### LINKED ISSUE #392: Project Octopus: Detached failed in static provisioned volume
Manual Test Done:

1. Provisioned volume statically.
2. Created Pod using the volume.
3. Deleted pod.

Observations:
1. Volume was attached successfully and pod was running.
2. Volume was not detached from node yet k8s reported volume detached successfully.

Log:
```
{"log":"I1121 20:53:54.523702       1 operation_generator.go:740] Verified volume is safe to detach for volume \"test-volume\" (UniqueName: \"kubernetes.io/vsphere-volume/[sharedVmfs-0] myDisk1\") on node \"kubernetes-node2\" \n","stream":"stderr","time":"2017-11-21T20:53:54.523770733Z"}
{"log":"I1121 20:53:54.535397       1 attacher.go:267] detach operation was successful. volume \"[sharedVmfs-0] myDisk1\" is already detached from node \"kubernetes-node2\".\n","stream":"stderr","time":"2017-11-21T20:53:54.535509134Z"}
{"log":"I1121 20:53:54.535584       1 operation_generator.go:368] DetachVolume.Detach succeeded for volume \"test-volume\" (UniqueName: \"kubernetes.io/vsphere-volume/[sharedVmfs-0] myDisk1\") on node \"kubernetes-node2\" \n","stream":"stderr","time":"2017-11-21T20:53:54.535602507Z"}
```

### PR DESCRIPTION
**Pull request by prashima**
Testing:

1. Deployed a pod with statically provisioned volume, created using vmkfstools -c 256M /vmfs/volumes/sharedVmfs-1/volumes/myDisk1.vmdk
2. Deleted pod
3. Made sure that the disk gets detached from the node where pod was running

Log messages:

{"log":"I1206 23:04:47.475452 1 virtualmachine.go:373] Found VirtualDisk backing with filename "[sharedVmfs-1] volumes/myDisk1.vmdk" for diskPath "[sharedVmfs-1] volumes/myDisk1"\n","stream":"stderr","time":"2017-12-06T23:04:47.48103635Z"}
{"log":"I1206 23:04:47.475517 1 vsphere.go:846] DiskIsAttached result: %!q(bool=true) and error: %!q(\u003cnil\u003e), for volume: "[sharedVmfs-1] volumes/myDisk1"\n","stream":"stderr","time":"2017-12-06T23:04:47.481092095Z"}

### CODE REVIEW

File: pkg/cloudprovider/providers/vsphere/vclib/virtualmachine.go [hunk 1]
```diff
@@ -362,12 +363,14 @@ func (vm *VirtualMachine) getVirtualDeviceByPath(ctx context.Context, diskPath s
...
 		return nil, err
 	}
+
 	// filter vm devices to retrieve device for the given vmdk file identified by disk path
 	for _, device := range vmDevices {
 		if vmDevices.TypeName(device) == "VirtualDisk" {
 			virtualDevice := device.GetVirtualDevice()
 			if backing, ok := virtualDevice.Backing.(*types.VirtualDiskFlatVer2BackingInfo); ok {
-				if backing.FileName == diskPath {
+				if matchVirtualDiskAndVolPath(backing.FileName, diskPath) {
```
Comment (shaominchen) [inline pkg/cloudprovider/providers/vsphere/vclib/virtualmachine.go]: Nit: How about renaming to virtualDiskMatchesVolPath?

**Comment by divyenpatel** [comment]
LGTM

File: pkg/cloudprovider/providers/vsphere/vclib/virtualmachine.go (hunk 1 above)
Comment (prashima) [reply pkg/cloudprovider/providers/vsphere/vclib/virtualmachine.go]: Root cause analysis available in issue itself https://github.com/vmware/kubernetes/issues/392
